### ISSUE TITLE
Seria possível adicionar essa feature?

### ISSUE THREAD

**Issue by alantody** [cleitonleonel/pyblaze#1]
Por exemplo no double sair assim no console

Giro anterior 9, cor Preto > Maior  = (Maior seria se tivesse dado preto e o valor total apostado no preto foi maior que o vermelho) ?

**Comment by cleitonleonel** [comment]
> Por exemplo no double sair assim no console
> 
> Giro anterior 9, cor Preto > Maior = (Maior seria se tivesse dado preto e o valor total apostado no preto foi maior que o vermelho) ?

Não sei se entendi direito essa sugestão, poderia apresentar algum exemplo prático dessa situação??? Desde já adianto que sim é possível adicionar uma saída com essas análises pedidas, mas sem um exemplo prático fica difícil implementar isso sem testes.

**Comment by alantody** [comment]
Por exemplo é bem simples, o bot vai fazer o calculo se a cor ganhadora a aposta era maior ou menor no montante total:

Preto    = R$1689,30
Vermelho = R$3938,80

Imagem explicativa: [https://i.imgur.com/PiYNqfD.png](url)


Nesse exemplo iria sair assim:

Giro anterior 10, cor Preto > Menor

**Comment by cleitonleonel** [comment]
> Por exemplo é bem simples, o bot vai fazer o calculo se a cor ganhadora a aposta era maior ou menor no montante total:
> 
> Preto = R$1689,30 Vermelho = R$3938,80
> 
> Imagem explicativa: https://i.imgur.com/PiYNqfD.png
> 
> Nesse exemplo iria sair assim:
> 
> Giro anterior 10, cor Preto > Menor

Certo, vou adicionar isso a saída incluindo um nova key com o valor dessa condição.

**Comment by cleitonleonel** [comment]
Issue sem resposta doa autor, então presumo que a atualização atendeu as necessidades do mesmo, fechando devido inatividade, sinta-se livre para reabri-lá quando assim for decidido.
