### ISSUE TITLE
Essa API é alugada?

### ISSUE THREAD

**Issue by CentroEducacional-CEC** [cleitonleonel/pyblaze#2]

**Comment by cleitonleonel** [comment]
@CentroEducacional-CEC a versão disponibilizada nesse projeto é free, porém possuo uma versão a qual eu comercializo, é uma versão com mais recursos e por isso mantenho privada, se trata de uma api desenvolvida com fastapi, e que pode ser hospedada em uma vps para alimentar outros apps.
Caso haja um interesse nessa versão privada me chame no telegram @CleitonLC ou pelo email cleiton.leonel@gmail.com .

**Comment by CentroEducacional-CEC** [comment]
A plataforma [BlazeAPI](https://pyblaze.herokuapp.com/docs), está offline!

**Comment by cleitonleonel** [comment]
> A plataforma [BlazeAPI](https://pyblaze.herokuapp.com/docs), está offline!

Sim esse link era da versão demo, não está mais ativo devido a mudança de políticas e cobrança do heroku.

**Comment by CentroEducacional-CEC** [comment]
Ecomo consifo essa api Free?

**Comment by cleitonleonel** [comment]
> Ecomo consifo essa api Free?

Bom, essa minha api vc não consegue de forma free, apenas pagando por ela, mas talvez tenha mais sorte continuando sua busca em outros repositórios.

**Comment by CentroEducacional-CEC** [comment]
Voce disse acima que tem uma free, e agora não tem mais? Meio confuso, mas ok! Já encontrei o que eu buscava.

**Comment by cleitonleonel** [comment]
> Voce disse acima que tem uma free, e agora não tem mais? Meio confuso, mas ok! Já encontrei o que eu buscava.

Só pra deixar claro que eu disse que a versão que está no projeto é a versão free, vc clona o projeto e ela está lá, já a versão demo era uma forma de usar a versão paga de forma limitada, mas como eu disse parou de funcionar devido as mudanças do heroku logo não existe mais versão demo disponível.
